// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAddress = "addresses"

// Address mapped from table <addresses>
type Address struct {
	Addrid     int64      `gorm:"column:addrid;type:bigint;primaryKey;autoIncrement:true" json:"addrid"`
	Postalcode *string    `gorm:"column:postalcode;type:longtext" json:"postalcode"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
