// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index:idx_users_deleted_at,priority:1" json:"deleted_at"`
	Name      *string        `gorm:"column:name;type:longtext" json:"name"`
	NameKana  *string        `gorm:"column:name_kana;type:longtext" json:"name_kana"`
	Age       *int64         `gorm:"column:age;type:bigint unsigned" json:"age"`
	Role      *Role          `gorm:"column:role;type:int" json:"role"`
	CompanyID *int64         `gorm:"column:company_id;type:bigint unsigned;index:fk_users_company,priority:1" json:"company_id"`
	Company   *Company       `gorm:"foreignKey:CompanyID" json:"company"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
